# Generated by Django 4.2.4 on 2023-08-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отдел'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='model',
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(max_length=200, verbose_name='Отдел'),
        ),
    ]
