# Generated by Django 4.2.4 on 2023-08-16 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_alter_device_options_remove_device_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Добавить город', 'verbose_name_plural': 'Город'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_name',
        ),
        migrations.AlterField(
            model_name='deviceinfield',
            name='analyzer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders_app.device', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='deviceinfield',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders_app.customer', verbose_name='Город/Область'),
        ),
        migrations.AlterField(
            model_name='deviceinfield',
            name='owner_status',
            field=models.TextField(verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='deviceinfield',
            name='serial_number',
            field=models.CharField(max_length=200, verbose_name='Серийный номер'),
        ),
    ]
