# Generated by Django 4.2.4 on 2023-08-16 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinfield',
            name='analyzer',
        ),
        migrations.RemoveField(
            model_name='deviceinfield',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='analyzer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='orders_app.device', verbose_name='Отдел'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='orders_app.customer', verbose_name='Город/Область'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deviceinfield',
            name='owner_status',
            field=models.TextField(verbose_name='Примичание'),
        ),
    ]
