# Generated by Django 4.2.4 on 2023-08-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0004_remove_deviceinfield_analyzer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfield',
            name='CharField',
            field=models.CharField(default=4, max_length=200, verbose_name='Наимеование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_city',
            field=models.CharField(max_length=200, verbose_name='Город'),
        ),
    ]
