# Generated by Django 4.2.4 on 2023-08-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0005_deviceinfield_charfield_alter_customer_customer_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceinfield',
            old_name='CharField',
            new_name='equipment',
        ),
    ]
