# Generated by Django 4.2.4 on 2023-08-18 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders_app', '0006_rename_charfield_deviceinfield_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='responsible_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Ответственные пользователи'),
        ),
        migrations.AlterField(
            model_name='deviceinfield',
            name='owner_status',
            field=models.TextField(blank=True, null=True, verbose_name='Примичание'),
        ),
    ]
