# Generated by Django 4.2.4 on 2023-08-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0008_order_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, upload_to='file', verbose_name='Прикрепить файл'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=44, max_length=200, verbose_name='Название задачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='url',
            field=models.URLField(default=3, verbose_name='Вставка ссылки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_description',
            field=models.TextField(verbose_name='Комментании'),
        ),
    ]
